term-project/final/config/routes.rb
Rails.application.routes.draw do
  root to: "article#index"

  #articles
  resources :article, only: [:index, :create, :new] do
  end

  get  "article/uploaded_articles", to: "article#uploaded_articles", as: "uploaded_articles"

  get  "article/:article_details_directoryID", to: "article#view", as: "view_article"
  post "article/upload", to: "article#upload"
  get  "article/update_article/:article_details_directoryID", to: "article#update_article", as: "update_article"
  post "article/commit_changes", to: "article#commit_changes"


  #users
  resources :user, only: [:index, :create, :new] do
  end

  get  "user/login", to: "user#login"
  get  "user/logout", to: "user#logout"
  post "user/auth", to: "user#auth"

  get  "user/calc_current_point", to: "user#calc_current_point"

  #transactions
  post "transaction/purchase_article", to: "transaction#purchase_article"
  get  "transaction/add_point", to: "transaction#add_point"
  post "transaction/purchase_point", to: "transaction#purchase_point"
  get  "transaction/purchase_history", to: "transaction#purchase_history"

end

term-project/final/app/controllers/article_controller.rb
class ArticleController < ApplicationController

  def index
    @articles = articles_builder
  end

  def view
    @article_summary = ArticleSummary.fetch_article_summary(params[:article_details_directoryID])
    @details = ArticleDetail.fetch_article_details(params[:article_details_directoryID])
    @contents = @details.fetch_article_contents.contents
    @is_obtained_article = is_obtained_article?(params[:article_details_directoryID])
    @is_author = is_author?(params[:article_details_directoryID])
  end

  def new
  end

  def upload
    created_at = Time.new
    updated_at = created_at

    article_summaries_directoryID  = @article_summaries_directoryID
    article_details_directoryID    = deepq_client.create_directory
    article_contents_directoryID   = deepq_client.create_directory
    purchased_users_directoryID    = deepq_client.create_directory

    register_current_user(article_summaries_directoryID)
    register_current_user(article_details_directoryID)
    register_current_user(article_contents_directoryID)

    #article_summaries_directoryID
      #dataDescription
        author_name                    = current_user.user_name
        author_public_hash             = current_user.user_public_hash
        created_at
        article_details_directoryID
        purchased_users_directoryID

        article_summary_data_description = article_summary_data_desciption_builder(author_name,\
          author_public_hash, created_at, article_details_directoryID, purchased_users_directoryID)

      #dataCertificate
        dataCertificate_summary      = article_details_directoryID

      #commit article summary
        article_summary = article_summary_builder(article_summary_data_description, dataCertificate_summary)
        commit_article_summary(article_summaries_directoryID, article_summary)

    #article_details_directoryID
      #offerPrice
        offerPrice                   = params[:offerPrice]

      #dataDescription
        title                        = params[:title]
        status                       = params[:status]
        summary                      = params[:summary]
        updated_at
        article_contents_directoryID

        article_details_data_description = article_details_data_description_builder(title, status, summary,\
          updated_at, article_contents_directoryID)

      #dataCertificate
        dataCertificate_details      = "version 0"

      #commit article details
        article_details = article_details_builder(offerPrice, article_details_data_description,\
          dataCertificate_details)
        commit_article_details(article_details_directoryID, article_details)

    #article contents directoryID
      #dataDescription
        dataDescription_contents     = params[:contents]
        created_at                   = Time.new

        article_contents_data_description = article_contents_data_description_builder(dataDescription_contents,\
          created_at)
      #dataCertificate
        dataCertificate_contents     = "version 0 part 0"

      #commit article contents
        article_contents = article_contents_builder(article_contents_data_description,\
          dataCertificate_contents)
        commit_article_contents(article_contents_directoryID, article_contents)

    redirect_to article_index_path
  end

  def update_article

    @contents = params[:contents]
    @article_details_directoryID = params[:article_details_directoryID]
    @is_author = is_author?(@article_details_directoryID)

    @article_details = ArticleDetail.fetch_article_details(@article_details_directoryID)
    @article_contents_directoryID = @article_details.article_contents_directoryID

    @current_version_number = @article_details.version.split(" ")[1].to_i
  end

  def commit_changes
    update_version_number = params[:current_version_number].to_i + 1

    article_details_directoryID = params[:article_details_directoryID]
    article_contents_directoryID = params[:article_contents_directoryID]

    #article_details_directoryID
      #offerPrice
        offerPrice                   = params[:offerPrice]

      #dataDescription
        title                        = params[:title]
        status                       = params[:status]
        summary                      = params[:summary]
        updated_at                   = Time.new
        article_contents_directoryID

        article_details_data_description = article_details_data_description_builder(title, status, summary,\
          updated_at, article_contents_directoryID)

      #dataCertificate
        dataCertificate_details      = "version #{update_version_number}"

      #commit article details
        article_details = article_details_builder(offerPrice, article_details_data_description,\
          dataCertificate_details)
        commit_article_details(article_details_directoryID, article_details)

    #article contents directoryID
      #dataDescription
        dataDescription_contents     = params[:contents]
        created_at                   = Time.new

        article_contents_data_description = article_contents_data_description_builder(dataDescription_contents,\
          created_at)
      #dataCertificate
        dataCertificate_contents     = "version #{update_version_number} part 0"

      #commit article contents
        article_contents = article_contents_builder(article_contents_data_description,\
          dataCertificate_contents)
        commit_article_contents(article_contents_directoryID, article_contents)
        
    if status == "deleted"
      redirect_to article_index_path
    else
      redirect_to view_article_path(article_details_directoryID)
    end
  end

  def uploaded_articles
    @uploaded_articles = []
    articles = articles_builder

    @uploaded_articles = articles.select{ |article| 
      article[:article_summary][:author_public_hash] == current_user.user_public_hash &&\
        article[:article_details].status != "deleted"
    }
  end

  private

  def articles_builder
    articles = []
    summary_array = deepq_client.list_data_entry(@article_summaries_directoryID)
    summary_array.each do |summary|
      article = []
      article_summary_arguments = JSON.parse(summary["dataDescription"])

      article_summary = ArticleSummary.new(article_summary_arguments)
      article_details = ArticleDetail.fetch_article_details(article_summary.article_details_directoryID)

      articles.push({article_summary: article_summary, article_details: article_details})
    end
    articles
  end

  # article summaries functions
  def article_summary_data_desciption_builder(author_name, author_public_hash, created_at,\
    article_details_directoryID, purchased_users_directoryID )

    article_summary_data_description =\
    { author_name: author_name,\
      author_public_hash: author_public_hash,\
      created_at: created_at,\
      article_details_directoryID: article_details_directoryID,\
      purchased_users_directoryID: purchased_users_directoryID }
  end

  def article_summary_builder(dataDescription, dataCertificate)
    article_summary = { dataDescription: dataDescription, dataCertificate: dataCertificate }
  end

  def commit_article_summary(article_summaries_directoryID, article_summary)
    directoryID     = article_summaries_directoryID
    userID          = current_user.user_public_hash
    password        = current_user.password
    offerPrice      = "0"
    dueDate         = "0"
    dataCertificate = article_summary[:dataCertificate]
    dataOwner       = current_user.user_public_hash
    dataDescription = article_summary[:dataDescription].to_json
    dataAccessPath  = "AnonJournal"

    deepq_client.create_data_entry(directoryID, userID, password, offerPrice, dueDate,\
      dataCertificate, dataOwner, dataDescription, dataAccessPath)
  end

  # article details functions
  def article_details_data_description_builder(title, status, summary, updated_at,\
    article_contents_directoryID)

    article_details_data_description = \
    { title: title,\
      status: status,\
      summary: summary,\
      updated_at: updated_at,\
      article_contents_directoryID: article_contents_directoryID }
  end

  def article_details_builder(offerPrice, dataDescription, dataCertificate)
    article_details = {offerPrice: offerPrice, dataDescription: dataDescription,\
      dataCertificate: dataCertificate}
  end

  def commit_article_details(article_details_directoryID, article_details)
    directoryID     = article_details_directoryID
    userID          = current_user.user_public_hash
    password        = current_user.password
    offerPrice      = article_details[:offerPrice]
    dueDate         = "0"
    dataCertificate = article_details[:dataCertificate]
    dataOwner       = current_user.user_public_hash
    dataDescription = article_details[:dataDescription].to_json
    dataAccessPath  = "AnonJournal"

    deepq_client.create_data_entry(directoryID, userID, password, offerPrice, dueDate,\
      dataCertificate, dataOwner, dataDescription, dataAccessPath)
  end

  #article contents functions
  def article_contents_data_description_builder(contents, created_at)
    article_contents_data_description = { contents: contents, created_at: created_at}
  end

  def article_contents_builder(dataDescription, dataCertificate)
    article_contents = {dataDescription: dataDescription, dataCertificate: dataCertificate }
  end

  def commit_article_contents(article_contents_directoryID, article_contents)
    word_count = article_contents[:dataDescription][:contents].length
    split_count = (word_count/one_content_max_word) + 1
    
    directoryID     = article_contents_directoryID
    userID          = current_user.user_public_hash
    password        = current_user.password
    offerPrice      = "0"
    dueDate         = "0"
    dataCertificate = article_contents[:dataCertificate]
    dataOwner       = current_user.user_public_hash
    #dataDescription
    dataAccessPath  = "AnonJournal"

term-project/final/app/helpers/article_helper.rb
module ArticleHelper
end

term-project/final/app/views/article/index.html.erb
<div class = "page-title">

  <div>
    <% if logged_in? %>
      <div>
        Hello! <%= current_user.user_name %>, You have <%= current_user.calc_current_point %> point!
      </div>
      <div>
        If you want more point? You can buy it from <%= link_to "here", transaction_add_point_path %>
      </div>
      <div>
        Your histories are <%= link_to "here", transaction_purchase_history_path %>
      </div>
      <div>
        Your uploaded articles are <%= link_to "here", uploaded_articles_path %>
      </div>
    <% end %>
  </div>

  <div>
  <% if logged_in? %>
    <%= link_to "Logout", user_logout_path %>
  <% else %>
    <div class ="user-registration">
      <%= link_to "user registration", new_user_path %>
    </div>

    <div>
      <%= link_to "Login", user_login_path %>
    </div>
  <% end %>
  </div>

  <%if logged_in? %>
    <div class = "upload-link">
      <%= link_to "Upload", new_article_path %>
    </div>
  <% end %>

  <p>Article List</p>

  <div class = "article-list">
    <% if @articles %>

      <% @articles.each do |article| %>
        <% if article[:article_details].status == "public" %>
          <div class = "article-list-member">
           <%= link_to article[:article_details].title, view_article_path(article_details_directoryID: article[:article_summary].article_details_directoryID) %> 
          </div>
          <div>
            <%= article[:article_details].summary %>
          </div>
        <% end %>
      <% end %>

    <% end %>
  </div>
</div>

term-project/final/app/views/article/new.html.erb
<div class = "page-title">
  Upload your article
</div>

<% if logged_in? %>
  <div class = "article-input_area">
    <%= form_with url: article_upload_path do |f| %>
      <div id="upload-form-title">
        <%= f.label "title : " %>
        <%= f.text_field :title %>
      </div>

      <div id="select-article-status">
        <%= f.select :status, [["public", "public"], ["private", "private"]], selected: "public" %>
      </div>

      <div id="upload-form-summary">
        <%= f.label "summary : " %>
        <%= f.text_field :summary %>
      </div>

      <div id="upload-form-contents">
        <%= f.label "contents : " %>
        <%= f.text_area :contents %>
      </div>

      <div id="upload-form-offer-price">
        <%= f.label "offer price : " %>
        <%= f.text_field :offerPrice %>
      </div>

      <div id="upload-form-submit">
        <%= f.submit "upload", data: { diesabled_with: "processing..." } %>
      </div>
    <% end %>
  </div>
<% else %>
  <div>
    Please login before posting an article.
  </div>
  <div>
    <%= link_to "Register", new_user_path %>
    <%= link_to "Login", user_login_path %>
  </div>
<% end %>

term-project/final/app/views/article/show.html.erb
<div id="article-title">
  <%= @article.fetch_title %>
</div>

<div id="article-author">
  Author : <%= User.find_by(user_hash: @article.owner_user_hash).user_name %>
</div>

<% if logged_in? %>
  <% if @is_obtained %>
    <div id="article-content">
      <%= @article.fetch_content %>
    </div>
  <% else %>
    <div id="price">
      <%= @article.fetch_offer_price %> point!
    </div>

    <%if @is_able_to_purchase %>
      <div id="purchase-article-button">
        <%= button_to "buy it now!", transaction_purchase_article_path(params: {article_id: @article.id} ) %>
      </div>
    <% else %>
      <div id="purchase-points-button">
        <%= button_to "purchase points", transaction_add_point_path, method: :get %>
      </div>
    <% end %>
  <% end %>
<% else %>
  <div>
    If you want to see? please login!
    <div class ="user-registration">
      <%= link_to "user registration", new_user_path %>
    </div>

    <div>
      <%= link_to "Login", user_login_path %>
    </div>
 </div>
<% end %>

term-project/final/app/views/article/update_article.html.erb
<div class = "page-title">
  Edit your article
</div>

<% if logged_in? && @is_author %>
  <div class = "article-input_area">
    <%= form_with url: article_commit_changes_path do |f| %>
      <%= f.hidden_field :current_version_number, value: @current_version_number %>
      <%= f.hidden_field :article_details_directoryID, value: @article_details_directoryID %>
      <%= f.hidden_field :article_contents_directoryID, value: @article_contents_directoryID %>

      <div id="upload-form-title">
        <%= f.label "title : " %>
        <%= f.text_field :title, value: @article_details.title %>
        Next version is ver.<%= @current_version_number + 1 %>
      </div>

      <div id="select-article-status">
        <%= f.select :status, [["public", "public"], ["private", "private",], ["delete", "deleted"]], selected: @article_details.status %>
      </div>

      <div id="upload-form-summary">
        <%= f.label "summary : " %>
        <%= f.text_field :summary, value: @article_details.summary%>
      </div>

      <div id="upload-form-contents">
        <%= f.label "contents : " %>
        <%= f.text_area :contents, value: @contents %>
      </div>

      <div id="upload-form-offer-price">
        <%= f.label "offer price : " %>
        <%= f.text_field :offerPrice, value: @article_details.offerPrice %>
      </div>

      <div id="upload-form-submit">
        <%= f.submit "update", data: { diesabled_with: "processing..." } %>
      </div>
    <% end %>
  </div>
<% end %>

term-project/final/app/views/article/uploaded_articles.html.erb
<div class = "page-title">
  uploaded articles
</div>

<% @uploaded_articles.each do |article| %>
  <div>
    <%= link_to article[:article_details].title, view_article_path(article[:article_summary].article_details_directoryID) %>
  </div>
<% end %>

term-project/final/app/views/article/view.html.erb
<div id="article-title">
  <%= @details.title %>
</div>

<div id="article-author">
  Author : <%= @article_summary.author_name %>
</div>

<% if logged_in? %>
  <% if @is_author %>
    <div id = "article-edit-button">
    <%= link_to "edit article", update_article_path(article_details_directoryID: @article_summary.article_details_directoryID, contents: @contents) %>
    <%= @details.version %>
    </div>
  <% end %>
  <% if @is_author || @is_obtained_article %>
    <div id="article-content">
      <%= @contents %>
    </div>
  <% else %>
    <div id="price">
      <%= @details.offerPrice %> point!
    </div>

    <%if has_enough_point?(@details.offerPrice.to_i) %>
      <div id="purchase-article-button">
        <%= button_to "buy it now!", transaction_purchase_article_path(article_details_directoryID: @article_summary.article_details_directoryID) %>
      </div>
    <% else %>
      <div id="purchase-points-button">
        <%= button_to "purchase points", transaction_add_point_path, method: :get %>
      </div>
    <% end %>
  <% end %>
<% else %>
  <div>
    If you want to see? please login!
    <div class ="user-registration">
      <%= link_to "user registration", new_user_path %>
    </div>

    <div>
      <%= link_to "Login", user_login_path %>
    </div>
 </div>
<% end %>